# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # ExternalUrlObject Model.
  class ExternalUrlObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The [Spotify URL](/documentation/web-api/concepts/spotify-uris-ids) for
    # the object.
    # @return [String]
    attr_accessor :spotify

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['spotify'] = 'spotify'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        spotify
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(spotify = SKIP)
      @spotify = spotify unless spotify == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      spotify = hash.key?('spotify') ? hash['spotify'] : SKIP

      # Create object from extracted values.
      ExternalUrlObject.new(spotify)
    end

    # Validates an instance of the object from a given value.
    # @param [ExternalUrlObject | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} spotify: #{@spotify}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} spotify: #{@spotify.inspect}>"
    end
  end
end
