# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # ExternalIdObject Model.
  class ExternalIdObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # [International Standard Recording
    # Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)
    # @return [String]
    attr_accessor :isrc

    # [International Article
    # Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%2
    # 9)
    # @return [String]
    attr_accessor :ean

    # [Universal Product
    # Code](http://en.wikipedia.org/wiki/Universal_Product_Code)
    # @return [String]
    attr_accessor :upc

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['isrc'] = 'isrc'
      @_hash['ean'] = 'ean'
      @_hash['upc'] = 'upc'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        isrc
        ean
        upc
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(isrc = SKIP, ean = SKIP, upc = SKIP)
      @isrc = isrc unless isrc == SKIP
      @ean = ean unless ean == SKIP
      @upc = upc unless upc == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      isrc = hash.key?('isrc') ? hash['isrc'] : SKIP
      ean = hash.key?('ean') ? hash['ean'] : SKIP
      upc = hash.key?('upc') ? hash['upc'] : SKIP

      # Create object from extracted values.
      ExternalIdObject.new(isrc,
                           ean,
                           upc)
    end

    # Validates an instance of the object from a given value.
    # @param [ExternalIdObject | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} isrc: #{@isrc}, ean: #{@ean}, upc: #{@upc}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} isrc: #{@isrc.inspect}, ean: #{@ean.inspect}, upc: #{@upc.inspect}>"
    end
  end
end
