# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # ManySimplifiedShows Model.
  class ManySimplifiedShows < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ShowBase]]
    attr_accessor :shows

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['shows'] = 'shows'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(shows = nil)
      @shows = shows
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      shows = nil
      unless hash['shows'].nil?
        shows = []
        hash['shows'].each do |structure|
          shows << (ShowBase.from_hash(structure) if structure)
        end
      end

      shows = nil unless hash.key?('shows')

      # Create object from extracted values.
      ManySimplifiedShows.new(shows)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} shows: #{@shows}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} shows: #{@shows.inspect}>"
    end
  end
end
