# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # ManyArtists Model.
  class ManyArtists < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ArtistObject]]
    attr_accessor :artists

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['artists'] = 'artists'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(artists = nil)
      @artists = artists
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      artists = nil
      unless hash['artists'].nil?
        artists = []
        hash['artists'].each do |structure|
          artists << (ArtistObject.from_hash(structure) if structure)
        end
      end

      artists = nil unless hash.key?('artists')

      # Create object from extracted values.
      ManyArtists.new(artists)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} artists: #{@artists}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} artists: #{@artists.inspect}>"
    end
  end
end
