# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # Markets Model.
  class Markets < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[String]]
    attr_accessor :markets

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['markets'] = 'markets'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        markets
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(markets = SKIP)
      @markets = markets unless markets == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      markets = hash.key?('markets') ? hash['markets'] : SKIP

      # Create object from extracted values.
      Markets.new(markets)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} markets: #{@markets}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} markets: #{@markets.inspect}>"
    end
  end
end
