# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # OAuth 2 scopes supported by the API
  class OAuthScopeEnum
    O_AUTH_SCOPE_ENUM = [
      # Communicate with the Spotify app on your device.

      APP_REMOTE_CONTROL = 'app-remote-control'.freeze,

      # Access your private playlists.

      PLAYLIST_READ_PRIVATE = 'playlist-read-private'.freeze,

      # Access your collaborative playlists.

      PLAYLIST_READ_COLLABORATIVE = 'playlist-read-collaborative'.freeze,

      # Manage your public playlists.

      PLAYLIST_MODIFY_PUBLIC = 'playlist-modify-public'.freeze,

      # Manage your private playlists.

      PLAYLIST_MODIFY_PRIVATE = 'playlist-modify-private'.freeze,

      # Access your saved content.

      USER_LIBRARY_READ = 'user-library-read'.freeze,

      # Manage your saved content.

      USER_LIBRARY_MODIFY = 'user-library-modify'.freeze,

      # Access your subscription details.

      USER_READ_PRIVATE = 'user-read-private'.freeze,

      # Get your real email address.

      USER_READ_EMAIL = 'user-read-email'.freeze,

      # Access your followers and who you are following.

      USER_FOLLOW_READ = 'user-follow-read'.freeze,

      # Manage your saved content.

      USER_FOLLOW_MODIFY = 'user-follow-modify'.freeze,

      # Read your top artists and content.

      USER_TOP_READ = 'user-top-read'.freeze,

      # Read your position in content you have played.

      USER_READ_PLAYBACK_POSITION = 'user-read-playback-position'.freeze,

      # Read your currently playing content and Spotify Connect devices
      # information.

      USER_READ_PLAYBACK_STATE = 'user-read-playback-state'.freeze,

      # Access your recently played items.

      USER_READ_RECENTLY_PLAYED = 'user-read-recently-played'.freeze,

      # Read your currently playing content.

      USER_READ_CURRENTLY_PLAYING = 'user-read-currently-playing'.freeze,

      # Control playback on your Spotify clients and Spotify Connect devices.

      USER_MODIFY_PLAYBACK_STATE = 'user-modify-playback-state'.freeze,

      # Upload images to Spotify on your behalf.

      UGC_IMAGE_UPLOAD = 'ugc-image-upload'.freeze,

      # Play content and control playback on your other devices.

      STREAMING = 'streaming'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_ENUM.include?(value)
    end
  end
end
