# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # PlaylistSnapshotId Model.
  class PlaylistSnapshotId < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :snapshot_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['snapshot_id'] = 'snapshot_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        snapshot_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(snapshot_id = SKIP)
      @snapshot_id = snapshot_id unless snapshot_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      snapshot_id = hash.key?('snapshot_id') ? hash['snapshot_id'] : SKIP

      # Create object from extracted values.
      PlaylistSnapshotId.new(snapshot_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} snapshot_id: #{@snapshot_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} snapshot_id: #{@snapshot_id.inspect}>"
    end
  end
end
