# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # PlaylistsFollowersRequest Model.
  class PlaylistsFollowersRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Defaults to `true`. If `true` the playlist will be included in user's
    # public playlists, if `false` it will remain private.
    # @return [TrueClass | FalseClass]
    attr_accessor :public

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['public'] = 'public'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        public
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(public = SKIP)
      @public = public unless public == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      public = hash.key?('public') ? hash['public'] : SKIP

      # Create object from extracted values.
      PlaylistsFollowersRequest.new(public)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} public: #{@public}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} public: #{@public.inspect}>"
    end
  end
end
