# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # RecommendationSeedObject Model.
  class RecommendationSeedObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The number of tracks available after min\_\* and max\_\* filters have been
    # applied.
    # @return [Integer]
    attr_accessor :after_filtering_size

    # The number of tracks available after relinking for regional availability.
    # @return [Integer]
    attr_accessor :after_relinking_size

    # A link to the full track or artist data for this seed. For tracks this
    # will be a link to a Track Object. For artists a link to an Artist Object.
    # For genre seeds, this value will be `null`.
    # @return [String]
    attr_accessor :href

    # The id used to select this seed. This will be the same as the string used
    # in the `seed_artists`, `seed_tracks` or `seed_genres` parameter.
    # @return [String]
    attr_accessor :id

    # The number of recommended tracks available for this seed.
    # @return [Integer]
    attr_accessor :initial_pool_size

    # The entity type of this seed. One of `artist`, `track` or `genre`.
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['after_filtering_size'] = 'afterFilteringSize'
      @_hash['after_relinking_size'] = 'afterRelinkingSize'
      @_hash['href'] = 'href'
      @_hash['id'] = 'id'
      @_hash['initial_pool_size'] = 'initialPoolSize'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        after_filtering_size
        after_relinking_size
        href
        id
        initial_pool_size
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(after_filtering_size = SKIP, after_relinking_size = SKIP,
                   href = SKIP, id = SKIP, initial_pool_size = SKIP,
                   type = SKIP)
      @after_filtering_size = after_filtering_size unless after_filtering_size == SKIP
      @after_relinking_size = after_relinking_size unless after_relinking_size == SKIP
      @href = href unless href == SKIP
      @id = id unless id == SKIP
      @initial_pool_size = initial_pool_size unless initial_pool_size == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      after_filtering_size =
        hash.key?('afterFilteringSize') ? hash['afterFilteringSize'] : SKIP
      after_relinking_size =
        hash.key?('afterRelinkingSize') ? hash['afterRelinkingSize'] : SKIP
      href = hash.key?('href') ? hash['href'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      initial_pool_size =
        hash.key?('initialPoolSize') ? hash['initialPoolSize'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      RecommendationSeedObject.new(after_filtering_size,
                                   after_relinking_size,
                                   href,
                                   id,
                                   initial_pool_size,
                                   type)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} after_filtering_size: #{@after_filtering_size}, after_relinking_size:"\
      " #{@after_relinking_size}, href: #{@href}, id: #{@id}, initial_pool_size:"\
      " #{@initial_pool_size}, type: #{@type}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} after_filtering_size: #{@after_filtering_size.inspect},"\
      " after_relinking_size: #{@after_relinking_size.inspect}, href: #{@href.inspect}, id:"\
      " #{@id.inspect}, initial_pool_size: #{@initial_pool_size.inspect}, type: #{@type.inspect}>"
    end
  end
end
