# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # SavedEpisodeObject Model.
  class SavedEpisodeObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The date and time the episode was saved.
    # Timestamps are returned in ISO 8601 format as Coordinated Universal Time
    # (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.
    # @return [DateTime]
    attr_accessor :added_at

    # Information about the episode.
    # @return [EpisodeObject]
    attr_accessor :episode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['added_at'] = 'added_at'
      @_hash['episode'] = 'episode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        added_at
        episode
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(added_at = SKIP, episode = SKIP)
      @added_at = added_at unless added_at == SKIP
      @episode = episode unless episode == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      added_at = if hash.key?('added_at')
                   (DateTimeHelper.from_rfc3339(hash['added_at']) if hash['added_at'])
                 else
                   SKIP
                 end
      episode = EpisodeObject.from_hash(hash['episode']) if hash['episode']

      # Create object from extracted values.
      SavedEpisodeObject.new(added_at,
                             episode)
    end

    def to_custom_added_at
      DateTimeHelper.to_rfc3339(added_at)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} added_at: #{@added_at}, episode: #{@episode}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} added_at: #{@added_at.inspect}, episode: #{@episode.inspect}>"
    end
  end
end
