# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # SimplifiedArtistObject Model.
  class SimplifiedArtistObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Known external URLs for this artist.
    # @return [ExternalUrlObject]
    attr_accessor :external_urls

    # A link to the Web API endpoint providing full details of the artist.
    # @return [String]
    attr_accessor :href

    # The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the
    # artist.
    # @return [String]
    attr_accessor :id

    # The name of the artist.
    # @return [String]
    attr_accessor :name

    # The object type.
    # @return [TypeEnum]
    attr_accessor :type

    # The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for
    # the artist.
    # @return [String]
    attr_accessor :uri

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['external_urls'] = 'external_urls'
      @_hash['href'] = 'href'
      @_hash['id'] = 'id'
      @_hash['name'] = 'name'
      @_hash['type'] = 'type'
      @_hash['uri'] = 'uri'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        external_urls
        href
        id
        name
        type
        uri
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(external_urls = SKIP, href = SKIP, id = SKIP, name = SKIP,
                   type = SKIP, uri = SKIP)
      @external_urls = external_urls unless external_urls == SKIP
      @href = href unless href == SKIP
      @id = id unless id == SKIP
      @name = name unless name == SKIP
      @type = type unless type == SKIP
      @uri = uri unless uri == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      external_urls = ExternalUrlObject.from_hash(hash['external_urls']) if hash['external_urls']
      href = hash.key?('href') ? hash['href'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      uri = hash.key?('uri') ? hash['uri'] : SKIP

      # Create object from extracted values.
      SimplifiedArtistObject.new(external_urls,
                                 href,
                                 id,
                                 name,
                                 type,
                                 uri)
    end

    # Validates an instance of the object from a given value.
    # @param [SimplifiedArtistObject | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} external_urls: #{@external_urls}, href: #{@href}, id: #{@id}, name:"\
      " #{@name}, type: #{@type}, uri: #{@uri}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} external_urls: #{@external_urls.inspect}, href: #{@href.inspect}, id:"\
      " #{@id.inspect}, name: #{@name.inspect}, type: #{@type.inspect}, uri: #{@uri.inspect}>"
    end
  end
end
