# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # UsersPlaylistsRequest Model.
  class UsersPlaylistsRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The name for the new playlist, for example `"Your Coolest Playlist"`. This
    # name does not need to be unique; a user may have several playlists with
    # the same name.
    # @return [String]
    attr_accessor :name

    # Defaults to `true`. If `true` the playlist will be public, if `false` it
    # will be private. To be able to create private playlists, the user must
    # have granted the `playlist-modify-private`
    # [scope](/documentation/web-api/concepts/scopes/#list-of-scopes)
    # @return [TrueClass | FalseClass]
    attr_accessor :public

    # Defaults to `false`. If `true` the playlist will be collaborative.
    # _**Note**: to create a collaborative playlist you must also set `public`
    # to `false`. To create collaborative playlists you must have granted
    # `playlist-modify-private` and `playlist-modify-public`
    # [scopes](/documentation/web-api/concepts/scopes/#list-of-scopes)._
    # @return [TrueClass | FalseClass]
    attr_accessor :collaborative

    # value for playlist description as displayed in Spotify Clients and in the
    # Web API.
    # @return [String]
    attr_accessor :description

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['public'] = 'public'
      @_hash['collaborative'] = 'collaborative'
      @_hash['description'] = 'description'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        public
        collaborative
        description
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name = nil, public = SKIP, collaborative = SKIP,
                   description = SKIP)
      @name = name
      @public = public unless public == SKIP
      @collaborative = collaborative unless collaborative == SKIP
      @description = description unless description == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : nil
      public = hash.key?('public') ? hash['public'] : SKIP
      collaborative = hash.key?('collaborative') ? hash['collaborative'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP

      # Create object from extracted values.
      UsersPlaylistsRequest.new(name,
                                public,
                                collaborative,
                                description)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name}, public: #{@public}, collaborative: #{@collaborative},"\
      " description: #{@description}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} name: #{@name.inspect}, public: #{@public.inspect}, collaborative:"\
      " #{@collaborative.inspect}, description: #{@description.inspect}>"
    end
  end
end
