# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApiWithFixesAndImprovementsFromSonallux
  # HttpCallBack allows defining callables for pre and post API calls.
  class HttpCallBack < CoreLibrary::HttpCallback
  end
end
