# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'spotify_web_api_with_fixes_and_improvements_from_sonallux'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include SpotifyWebApiWithFixesAndImprovementsFromSonallux
  include CoreLibrary

  # Create configuration and set any test parameters
  def create_configuration
    Configuration.new(http_callback: HttpResponseCatcher.new)
  end

  # Initializes the base test controller
  def setup_class
    _config = create_configuration
    @client = Client.new(config: _config)

    oauth_2_0_token = @client.oauth_2_0.fetch_token('910b000d4f')
    authorization_code_auth_credentials = _config.authorization_code_auth_credentials.clone_with(o_auth_token: oauth_2_0_token)
    _config = _config.clone_with(authorization_code_auth_credentials: authorization_code_auth_credentials)
    @client = Client.new(config: _config)  end
end
