# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class CategoriesControllerTest < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.categories
    @response_catcher = @controller.http_call_back
  end

  # Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
  #
  def test_get_categories
    # Parameters for the API call
    locale = 'sv_SE'
    limit = 20
    offset = 0

    # Perform the API call through the SDK function
    result = @controller.get_categories(locale: locale, limit: limit,
                                        offset: offset)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
  #
  def test_get_a_category
    # Parameters for the API call
    category_id = 'dinner'
    locale = 'sv_SE'

    # Perform the API call through the SDK function
    result = @controller.get_a_category(category_id, locale: locale)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end