# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class EpisodesControllerTest < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.episodes
    @response_catcher = @controller.http_call_back
  end

  # Get Spotify catalog information for a single episode identified by its
  #unique Spotify ID.
  #
  def test_get_an_episode
    # Parameters for the API call
    id = '512ojhOuo1ktJprKbVcKyQ'
    market = 'ES'

    # Perform the API call through the SDK function
    result = @controller.get_an_episode(id, market: market)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Get Spotify catalog information for several episodes based on their Spotify IDs.
  #
  def test_get_multiple_episodes
    # Parameters for the API call
    ids = '77o6BIVlYM3msb4MMIL1jH,0Q86acNRm6V9GYx55SXKwf'
    market = 'ES'

    # Perform the API call through the SDK function
    result = @controller.get_multiple_episodes(ids, market: market)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Get a list of the episodes saved in the current Spotify user's library.<br/>
  #This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
  #
  def test_get_users_saved_episodes
    # Parameters for the API call
    market = 'ES'
    limit = 20
    offset = 0

    # Perform the API call through the SDK function
    result = @controller.get_users_saved_episodes(market: market, limit: limit,
                                                  offset: offset)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Save one or more episodes to the current user's library.<br/>
  #This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
  #
  def test_save_episodes_user
    # Parameters for the API call
    ids = '77o6BIVlYM3msb4MMIL1jH,0Q86acNRm6V9GYx55SXKwf'
    body = nil

    # Perform the API call through the SDK function
    @controller.save_episodes_user(ids, body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

  # Remove one or more episodes from the current user's library.<br/>
  #This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
  #
  def test_remove_episodes_user
    # Parameters for the API call
    ids = '7ouMYWpwJ422jRcDASZB7P,4VqPOruhp5EdPBeR92t6lQ,2takcwOaAZWiXQijPHIx7B'
    body = nil

    # Perform the API call through the SDK function
    @controller.remove_episodes_user(ids, body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

  # Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.<br/>
  #This API endpoint is in __beta__ and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
  #
  def test_check_users_saved_episodes
    # Parameters for the API call
    ids = '77o6BIVlYM3msb4MMIL1jH,0Q86acNRm6V9GYx55SXKwf'

    # Perform the API call through the SDK function
    result = @controller.check_users_saved_episodes(ids)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    assert_equal("[\r\n  false,\r\n  true\r\n]", @response_catcher.response.raw_body)
  end

end