# spotify_web_api_with_fixes_and_improvements_from_sonallux
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'

require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'

require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'api_helper'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'client'

# Utilities
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'utilities/file_wrapper'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'utilities/date_time_helper'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'utilities/union_type_lookup'

# Http
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'http/http_call_back'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'http/http_method_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'http/http_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'http/http_response'

# Logger
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'http/auth/o_auth2'

# Models
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/base_model'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/linked_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/track_restriction_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/album_restriction_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/episode_restriction_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/chapter_restriction_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/artist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/simplified_artist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/play_history_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/queue_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/currently_playing_context_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/disallows_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/error_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/private_user_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/public_user_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/audio_analysis_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/time_interval_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/section_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/segment_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/audio_features_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/simplified_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/device_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/cursor_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/cursor_paging_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/cursor_paging_play_history_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/cursor_paging_simplified_artist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_playlist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_featured_playlist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_artist_discography_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_saved_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_saved_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_playlist_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_show_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_saved_show_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_episode_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_saved_episode_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_audiobook_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_artist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_simplified_chapter_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/recommendations_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/recommendation_seed_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/saved_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/saved_track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/saved_episode_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/saved_show_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/simplified_playlist_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_tracks_ref_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_user_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_owner_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/category_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/track_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/episode_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/episode_base'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/resume_point_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/show_base'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/show_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/audiobook_base'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/audiobook_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/album_base'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/simplified_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/artist_discography_album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/chapter_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/chapter_base'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/album_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/context_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/copyright_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/author_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/narrator_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/external_id_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/external_url_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/followers_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/image_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/explicit_content_settings_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/currently_playing_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/saved_audiobook_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paging_saved_audiobook_object'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/categories'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/cursor_paged_artists'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_albums'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_artists'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_audiobooks'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_audio_features'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_chapters'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_devices'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_episodes'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_genres'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_simplified_shows'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/many_tracks'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/markets'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_albums_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_episodes_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_episodes_request1'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_following_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_following_request1'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_player_play_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_player_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_shows_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_tracks_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/me_tracks_request1'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/meta'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paged_albums'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/paged_categories'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlists_followers_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlists_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlists_tracks_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlists_tracks_request1'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlists_tracks_request2'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/playlist_snapshot_id'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/search_items'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/track'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/track1'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/users_playlists_request'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/o_auth_token'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/album_group_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/album_type_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/include_external_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/item_type_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/item_type1_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/item_type2_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/item_type3_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/mode_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/reason_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/release_date_precision_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/type_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/type2_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/type3_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/type5_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/o_auth_provider_error_enum'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'models/o_auth_scope_enum'

# Exceptions
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/api_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/bad_request_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/forbidden_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/not_found_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/too_many_requests_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/unauthorized_exception'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'exceptions/o_auth_provider_exception'

require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'configuration'

# Controllers
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/base_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/albums_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/artists_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/audiobooks_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/categories_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/chapters_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/episodes_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/genres_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/markets_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/player_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/playlists_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/search_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/shows_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/tracks_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/users_controller'
require_relative 'spotify_web_api_with_fixes_and_improvements_from_sonallux/' \
                 'controllers/o_auth_authorization_controller'
